#!/usr/bin/ruby

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

sum = 0
previous = 1
current = 2

while (previous <= 4_000_000) do
    previous, current = current, previous
    current += previous
    sum += previous if previous.even?
end

puts sum
